### PR TITLE
#6, Support chunked responses, e.g. no Content-Length header

### PR DESCRIPTION
**Pull request by rotemreiss**

### CODE REVIEW

**Review by yassineaboukir — APPROVED** [review]
Computing the response body length should be a good alternative to content-length header. And the new `getcontentlength()` function should also reduce redundancy in the code. Thanks @rotemreiss!

@clirimemini will review and approve changes.

**Review by yassineaboukir — APPROVED** [review]
Agreed it should be converted to string to allow comparison.

**Comment by rotemreiss** [comment]
@yassineaboukir @clirimemini Can we merge it?

**Comment by clirimemini** [comment]
I'm updating Keye, it will compute the response body length instead of getting the Content-Length header. Thanks 👍

**Pull request closed without merging**
